### ISSUE TITLE
[1.1] Can't Backup More Than One Network At a Time

### ISSUE THREAD

**Issue by saphtea** [LiquidFenrir/WifiManager#3]
Device: New 3DS XL
CFW: Luma

When I open the app up, I can back up one network, it'll take a second, then that backup will show up in the list. Then if I backup a different slot, even after confirming the name of the backup the name doesn't show up on the list and a backup is not completed. I need to close out of the app after each back up in order to backup multiple wifi networks.

**Comment by LiquidFenrir** [comment]
I'll investigate, but maybe try not to go as fast? You might have hit the protection put in place to prevent duplicates, if you press the buttons in the same second

**Comment by LiquidFenrir** [comment]
Hmm, indeed could reproduce. needs researching for now

**Comment by LiquidFenrir** [comment]
This should be fixed with the v1.1.1 release, can you confirm? will close once you do

**Comment by saphtea** [comment]
I think it's working now..... but the saved networks on the list seems to disappear. It looks blank, but when I go up and down with the directional pad I can still see info about the saved networks on the top of the screen. So all of the saved networks are still there, the list just isn't being displayed. Did you want me to report another issue for this?

**Comment by LiquidFenrir** [comment]
is it fixed with v1.1.2 ? It should be, can you confirm?

**Comment by saphtea** [comment]
Confirmed and now works as expected, thank you!

**Comment by LiquidFenrir** [comment]
Perfect, closing then, thanks!
